const facts = [
  "Im Jahr 1987 überholten Katzen die Hunde als Nr.1 Haustier in Amerika.",
  "Katzen, die zusammenleben, reiben manchmal ihre Köpfe zusammen, um zu signalisieren, dass sie keine Absicht haben zu kämpfen. Dies ist vermehrt bei jüngeren Katzen zu beobachten - vorallem wenn sie aufgeregt sind.",
  "Die Katzenmutter bringt ihren Kitten bei das Katzenklo zu verwenden",
  "Um catfacts zu deabonnieren antworte mit dem folgenden Code: tj3G5de$se",
  "Das ist aber schade! Bist du sicher, dass du catfacts deabonnieren willst? Antworte mit YES oder NO",
  "Ungültiger Befehl, CatFacts!",
  "Die Art wie du deine Kitten im jungen Alter behandelst wird Einfluss auf dessen Persönlichkeit im höheren Alter haben.",
  "Entgegen der läufigen Meinung ist die Katze ein soziales Tier. Eine Hauskatze wird auf Sprache reagieren und antworten und scheint menschliche Gesellschaft zu genießen.",
  "Bei guter Behandlung können Katzen bis zu 20 oder mehr Jahre alt werden. Die durchschnittliche Lebenserwartung einer Hauskatze beträgt allerdings 14 Jahre.",
  "Das Kastrieren einer Katze verlängert ihre Lebenserwartung um zwei bis drei Jahre.",
  "Um catfacts zu deabonnieren antworte mit dem folgenden Code: tj3G5de$se",
  "Das ist aber schade! Bist du sicher, dass du catfacts deabonnieren willst? Antworte mit YES oder NO",
  "Ungültiger Befehl, CatFacts!",
  "Katzen, vorallem ältere Katzen, sind in der Lage Krebs zu bekommen. Oftmals kann diese Krankheit erfolgreich behandelt werden.",
  "Katzen können süß nicht schmecken",
  "Katzen benötigen Fett in ihrem Diätfutter, da sie dieses nicht selbst produzieren können.",
  "Einige übliche Hauspflanzen sind giftig für Katzen. Darunter sind: Efeu, Schwertlilie, Mistelzweig, Philodendron und Eibe.",
  "Tylenol und Schokolade sind für Katzen giftig.",
  "Viele Katzen können Kuhmilch nicht richtig verdauen. Milch und Milchprodukte sorgen daher für Durchfall bei Katzen.",
  "Die durchschnittliche Katzenfutter Portion ist equivalent zu ungefähr fünf Mäusen.",
  "Katzen können durch das Fressen von Flöhen Bandwürmer bekommen. Diese Würmer leben für immer in der Katze, oder bis sie mit Medikamenten entfernt werden. Sie vermehren sich, indem sie ein Glied am Ende ihres langen Körpers abwerfen. Dieses Glied krabbelt aus dem Anus der Katze und legt Hunderte von Eiern ab. Diese Eier werden von Flohlarven aufgenommen, und der Kreislauf setzt sich fort. Auch Menschen können diese Bandwürmer bekommen, aber nur, wenn sie infizierte Flöhe essen. Katzen mit Bandwürmern sollten von einem Tierarzt entwurmt werden.",
  "Katzen können durch das Fressen von Mäusen Bandwürmer bekommen. Wenn deine Katze eine Maus fängt, ist es am besten, ihr die Beute wegzunehmen.",
  "Es existiert eine Katzen Variante von AIDS.",
  "Die Farbe der Punkte bei Siamkatzen ist wärmebedingt. Kühle Bereiche sind dunkler.",
  "Siamesische Kitten werden, aufgrund der Hitze im Uterus der Mutter, weiß geboren. Diese Wärme verhindert, dass sich die Haare der Kitten verdunkeln.",
  "Katzenallergiker sind eigentlich gegen Katzenspeichel oder Katzenschuppen allergisch. Wenn die Hauskatze regelmäßig gebadet wird, wird sie von den Allergikern besser vertragen.",
  "Studien zeigen, dass das Allergen bei Katzen mit ihren Duftdrüsen zusammenhängt. Katzen haben Duftdrüsen im Gesicht und an der Schwanzwurzel. Ausgewachsene Kater erzeugen den meisten Duft. Wenn dieses Sekret aus den Duftdrüsen das Allergen ist, sollten Allergiker kastrierte weibliche Katzen am besten vertragen.",
  "Katzen denken nicht, dass sie kleine Menschen sind. Sie denken, dass wir große Katzen sind. Das beeinflusst ihr Verhalten in vielerlei Hinsicht.",
  "Katzen sind anfällig für Zahnfleischerkrankungen und Zahnkaries. Sie sollten ihre Zähne einmal im Jahr vom Tierarzt oder vom Katzenzahnarzt reinigen lassen.",
  "Viele Menschen befürchten, sich bei Katzen mit einer Protozoenerkrankung, der Toxoplasmose, anzustecken. Diese Krankheit kann beim Menschen Krankheiten hervorrufen, aber noch schlimmer ist, dass sie bei Ungeborenen zu Missbildungen führen kann. Toxoplasmose ist eine weit verbreitete Krankheit, die manchmal über den Kot von Katzen übertragen wird. Sie wird am häufigsten durch den Verzehr von rohem oder seltenem Rindfleisch verursacht. Schwangere Frauen und Menschen mit einem geschwächten Immunsystem sollten das Katzenklo nicht berühren. Ansonsten gibt es keinen Grund, warum diese Menschen Katzen meiden sollten.",
  "Der Vorfahre aller Hauskatzen ist die Afrikanische Wildkatze, die auch heute noch existiert.",
  "Im alten Ägypten war das Töten einer Katze ein Verbrechen, das mit dem Tod bestraft wurde.",
  "Im alten Ägypten wurden Katzenmumien angefertigt, und einbalsamierte Mäuse wurden mit ihnen in die Gräber gelegt. In einer alten Stadt wurden über 300.000 Katzenmumien gefunden.",
  "Im Mittelalter wurden, während des Johannisfestes, Katzen auf den Plätzen der Städte lebendig verbrannt.",
  "Die erste Katzenshow fand 1871 im Crystal Palace in London statt.",
  "Heute gibt es etwa 100 verschiedene Rassen der Hauskatze.",
  "Wie Vögel verfügen auch Katzen über ein Heimfindevermögen. Dieses nutzt ihre biologische Uhr, den Sonnenstand und das Magnetfeld der Erde. Eine Katze, die sich weit von ihrem Zuhause entfernt hat, kann dorthin zurückfinden. Aber wenn die Besitzer einer Katze sich weit von ihrem Zuhause entfernen, kann die Katze sie nicht mehr finden.",
  "Katzen vergraben ihren Kot, um ihre Spuren vor Raubtieren zu verbergen.",
  "Katzen schlafen 16 bis 18 Stunden am Tag. Wenn Katzen schlafen, sind sie immer noch wachsam gegenüber eingehenden Reizen. Stupst man eine schlafenden Katze am Schwanz an, reagiert sie entsprechend.",
  "Außer mit der Nase können Katzen auch mit einem zusätzlichen Organ riechen, dem so genannten Jacobsonschen Organ, das sich an der Oberseite des Mundes befindet.",
  "Das Chlor in frischem Leitungswasser reizt die empfindliche Katzennase. Lass Leitungswasser 24 Stunden lang stehen, bevor du es einer Katze gibst.",
  "Abraham Lincoln liebte Katzen. Er hatte vier, als er im weißen Haus lebte.",
  "Julius Caesar, Henri II, Charles XI und Napoleon hatten alle Angst vor Katzen.",
  "Katzen haben im Durchschnitt 24 Schnurrhaare, die in vier horizontalen Reihen auf jeder Seite angeordnet sind.",
  "Das Wort 'Katze' in verschiedenen Sprachen: Französisch: chat; Deutsch: Katze; Italienisch: gatto; Spanisch/Portugiesisch: gato; Jiddisch: kats; Maltesisch: qattus; Schwedisch/Norwegisch: katt; Niederländisch: kat; Isländisch: kottur; Griechisch: catta; Hindu: katas; Japanisch:neko; Polnisch: kot; Ukrainisch: kotuk; Hawiianisch: popoki; Russisch: koshka; Latein: cattus; Ägyptisch: mau; Türkisch: kedi; Armenisch: Gatz; Chinesisch: mio; Arabisch: biss; Indonesisch: qitta; Bulgarisch: kotka; Malaiisch: kucing; Thailändisch/Vietnamesisch: meo; Rumänisch: pisica; Litauisch: katinas; Tschechisch: kocka; Slowakisch: macka; Armenisch: gatz; Baskisch: catua; Estnisch: kass; Finnisch: kissa; Suaheli: paka.",
  "Statistiken zeigen, dass Tierliebhaber in den letzten Jahren Katzen gegenüber Hunden bevorzugt haben!",
  "Katzen kann man beibringen, an der Leine zu gehen. Dies erfordert jedoch viel Zeit und Geduld. Je jünger die Katze ist, desto einfacher ist es für sie zu lernen.",
  "Schnurren bedeutet nicht immer Freude. Schnurren kann bedeuten, dass eine Katze schreckliche Schmerzen hat, z.B. bei der Geburt eines Kindes. Kitten schnurren ihrer Mutter zu, um ihr mitzuteilen, dass sie beim Säugen genug Milch bekommen. Das Schnurren ist ein Vorgang des Ein- und Ausatmens, der normalerweise mit geschlossenem Maul ausgeführt wird. Aber keine Sorge, wenn deine Katze schnurrt, während du sie sanft streichelst und mit ihr kuschelst - dann ist sie eine glückliche Katze!",
  "Die Katzenminze enthält ein Öl namens Hepetalacton, das bei Katzen das bewirkt, was Marihuana bei manchen Menschen bewirkt. Nicht alle Katzen reagieren darauf, aber die, die darauf reagieren, scheinen in einen tranceartigen Zustand zu geraten. Eine positive Reaktion äußert sich darin, dass die Katze an der Katzenminze schnüffelt, dann leckt, beißt, kaut, sich wiederholt darauf reibt und wälzt, schnurrt, miaut und sogar in die Luft springt.",
  "Von allen Katzenarten ist die Hauskatze die einzige Art, die ihren Schwanz beim Laufen senkrecht halten kann. Alle Wildkatzenarten halten ihren Schwanz beim Laufen waagerecht oder zwischen den Beinen eingeklemmt.",
  "Eine glückliche Katze hält ihren Schwanz hoch und fest.",
  "Fast 10% der Knochen einer Katze befinden sich im Schwanz, und der Schwanz dient dazu, das Gleichgewicht zu halten.",
  "Katzenfamilien spielen in der Regel am besten in gerader Zahl. Katzen und Kitten sollten nach Möglichkeit paarweise angeschafft werden.",
  "Backschokolade ist die gefährlichste Schokolade für Katzen.",
  "Den Puls einer Katze prüft man an der Innenseite des hinteren Oberschenkels, wo das Bein mit dem Körper verbunden ist. Normal für Katzen: 110-170 Schläge pro Minute.",
  "Jaguare sind die einzigen Großkatzen, die nicht brüllen.",
  "Das Sichtfeld einer Katze beträgt etwa 185 Grad.",
  "Katzen haben individuelle Vorlieben für Kratzflächen und -winkel. Einige kratzen horizontal, während andere ihr Kratzen vertikal ausüben.",
  "Die Maine Coone ist die einzige in Amerika beheimatete Langhaarrasse.",
  "Die Maine Coon ist 4 bis 5 Mal größer als die Singapura, die kleinste Katzenrasse.",
  "Man nimmt an, dass die Tabby-Katzen ihren Namen von Attab, einem Stadtteil von Bagdad, der heutigen Hauptstadt des Irak, haben.",
  "Einziehbare Krallen sind ein physikalisches Phänomen, das Katzen vom Rest des Tierreichs unterscheidet. In der Familie der Katzen können nur Geparden ihre Krallen nicht einziehen.",
  "Nicht jede Katze wird von Katzenminze 'high'. Ob eine Katze darauf anspricht oder nicht, hängt von einem rezessiven Gen ab: Kein Gen, keine Freude.",
  "Eine Katze kann mit einer Geschwindigkeit von ca. 50 Kilometer pro Stunde sprinten.",
  "Im alten Ägypten rasierten sich alle Familienmitglieder beim Tod einer Familienkatze die Augenbrauen als Zeichen der Trauer.",
  "Katzen werden erst halb so lange domestiziert wie Hunde.",
  "Man nimmt an, dass die Schnurrhaare einer Katze eine Art Radar sind, mit dessen Hilfe sie den Raum, durch den sie gehen will, abschätzen kann.",
  "Eine Katze kann fünf oder mehr Stunden am Tag damit verbringen, sich zu pflegen.",
  "Alle Katzen haben drei Gruppen von langen Haaren, die druckempfindlich sind - Schnurrhaare, Augenbrauen und die Haare zwischen den Pfotenballen.",
  "Menschen und Katzen haben identische Regionen im Gehirn, die für Emotionen zuständig sind.",
  "Um catfacts zu deabonnieren antworte mit dem folgenden Code: tj3G5de$se",
  "Das ist aber schade! Bist du sicher, dass du catfacts deabonnieren willst? Antworte mit YES oder NO",
  "Ungültiger Befehl, CatFacts!",
  "Das Gehirn einer Katze ist dem eines Menschen ähnlicher als dem eines Hundes.",
  "Eine Katze hat mehr Knochen als der Mensch; Der Mensch hat 206, die Katze 230 Knochen.",
  "Katzen haben 30 Wirbel - 5 mehr als Menschen.",
  "Katzen sind das beliebteste Haustier in den Vereinigten Staaten: Es gibt 88 Millionen Hauskatzen und 74 Millionen Hunde.",
  "Katzen haben mehr als 20 Muskeln, die ihre Ohren steuern.",
  "Eine Gruppe von Katzen nennt man Wurf.",
  "Es gibt Katzen, die Stürze aus über 32 Stockwerken (320 Metern) auf Beton überlebt haben.",
  "Katzen schlafen 70% ihres Lebens.",
  "Ein Kater ist seit 15 Jahren Bürgermeister von Talkeetna, Alaska. Sein Name ist Stubbs.",
  "Eine Katze hat 2013 für das Amt des Bürgermeisters von Mexiko-Stadt kandidiert.",
  "Bei Tigern und Tabbies ist die Mitte der Zunge mit nach hinten gerichteten Stacheln bedeckt, die zum Abreißen und Festhalten von Fleisch dienen.",
  "Wenn Katzen Grimassen schneiden, sind sie in der Regel 'geschmackssuchend'. Sie haben ein zusätzliches Organ, das es ihnen ermöglicht, bei kontrollierter Atmung, die Luft zu schmecken.",
  "Katzen können keine Süße schmecken.",
  "Das Besitzen einer Katze kann das Risiko eines Schlaganfalls oder Herzinfarkts um ein Drittel senken.",
  "Wikipedia hat eine Aufnahme einer miauenden Katze - warum auch nicht?",
  "Die größte Katze der Welt war 123,19 cm lang. https://www.youtube.com/watch?v=gc5M0aGc_EI",
  "Es gibt Hinweise darauf, dass domestizierte Katzen seit 3600 v. Chr. existieren, also 2.000 Jahre vor den ägyptischen Pharaonen.",
  "Das Schnurren einer Katze kann eine Form der Selbstheilung sein, da es sowohl ein Zeichen für Nervosität als auch für Zufriedenheit sein kann.",
  "Die Frequenz des Schnurrens einer Hauskatze ist die Gleiche, mit der sich Muskeln und Knochen selbst reparieren.",
  "Erwachsene Katzen miauen nur, um mit Menschen zu kommunizieren.",
  "Die reichste Katze der Welt ist 13 Millionen Dollar wert. Nachdem ihre Besitzerin verstorben ist, hat sie ihm ihr Vermögen hinterlassen.",
  "Deine Katze erkennt deine Stimme, tut aber so, als wäre sie zu cool, um sich darum zu kümmern (wahrscheinlich, weil sie es ist).",
  "Katzen sind oft laktoseintolerant, also gib ihnen keine Milch!",
  "Katzen können bis zum Sechsfachen ihrer Körperlänge hoch springen.",
  "Katzen haben zum Aussterben von 33 verschiedenen Arten beigetragen.",
  "Katzen können Meerwasser trinken, um zu überleben.",
];
const langName = "german",
  langISO = "deu",
  langLocale = "de",
  langLocaleName = "germany";

module.exports = {
  langName,
  langISO,
  langLocale,
  langLocaleName,
  code: `${langISO}-${langLocale}`,
  codeName: `${langName} (${langLocaleName})`,
  facts: facts,
};
