const facts = [
  "Noong 1987, naunahan ng mga pusa ang aso bilang pinaka-sikat na alagang hayop sa America",
  "Ang mga pusa na nakatirang magkasama ay minsan ay nag-aalab ng ulo ng isa't isa upang ipakita na walang intensyon na maglaban. Mas madalas itong ginagawa ng mga bata na pusa, lalo na kapag sila ay nae-excite.",
  "Tinuturuan ng mga ina ang kanilang mga alagang kuting na gumamit ng litter box.",
  "Ang pagtrato mo sa mga pusa sa maagang yugto ng kanyang buhay ay magbibigay ng kanyang mga katangian ng pagkatao sa hinaharap.",
  "Sa kabila ng popular na paniniwala, ang pusa ay sosyal na hayop. Ang isang alagang pusa ay tumutugon sa pagsasalita, at parang nagugustuhan ang kasamaan ng tao.",
  "Kapag inaalagaan ng maayos, ang isang pusa ay maaaring mabuhay ng labing-dalawa o higit pa na taon ngunit ang karaniwang buhay ng isang pambahay na pusa ay labing-apat na taon.",
  "Ang pagkakapon ng pusa ay nagpapadami ng dalawang o tatlong taong buhay ng pusa.",
  "Ang mga pusa, lalo na ang mga matatandang pusa, ay nagkakaroon ng kanser. Maraming beses ay maaring magamot nang maayos ang sakit na ito.",
  "Hindi makalasa ng matamis ang pusa.",
  "Kailangan ng mga pusa na may taba sa kanilang diyeta dahil hindi sila makagawa nito nang sarili nila.",
  "Ilan sa mga pangkaraniwang halaman sa bahay na nakakalason sa mga pusa ay ang English Ivy, iris, mistletoe, philodendron, at yew.",
  "Nakakalason sa pusa ang Tylenol at tsokolate.",
  "Maraming mga pusa ang hindi makakapag-digest ng gatas ng baka. Ang gatas at mga produkto ng gatas ay nagbibigay sa kanila ng pagtatae.",
  "Ang karaniwang pagkain ng pusa ay katumbas ng halos limang daga.",
  "Maaaring makakuha ang mga pusa ng tapeworm mula sa pagkain ng mga pulgas. Ang mga worm na ito ay naninirahan sa loob ng pusa para magpakailanman, o hanggang sila ay alisin sa pamamagitan ng gamot. Sila ay nagpaparami sa pamamagitan ng pag-shed ng isang link mula sa huli ng kanilang mababang katawan. Ang link na ito ay lumalabas sa pwet ng pusa, at nag-shed ng daan-daang itlog. Ang mga itlog na ito ay kinakain ng mga larawan ng pulgas, at ang cycle ay nagpapatuloy.",
  "Maaaring makakuha ng tapeworm ang mga pusa mula sa pagkain ng mga daga. Kung nahuli ng iyong pusa ang isang daga, ang pinakamabuting gawin ay alisin ang premyo mula sa kanya.",
  "Isang uri ng AIDS ay umiiral sa mga pusa.",
  "Ang kulay ng mga punto sa Siamese cats ay nakasalalay sa init. Ang mga malamig na lugar ay mas madilim.",
  "Ang mga Siamese na kuting ay ipinanganak na puti dahil sa init sa loob ng matris ng ina bago ang pagkapanganak. Pinapanatili ng init na ito ang buhok ng mga kuting na hindi madilim sa mga puntos.",
  "Ang mga taong may alerhiya sa mga pusa ay may alerhiya sa laway ng pusa o sa dander ng pusa. Kung ang residenteng pusa ay palagi nang binababad, mas mababawasan ang pagiging alerdyi ng mga taong may alerhiya.",
  "Ngayon ay ipinapakita ng mga pag-aaral na ang allergen sa mga pusa ay may kaugnayan sa kanilang mga scent gland. Mayroong mga scent gland ang mga pusa sa kanilang mukha at sa base ng kanilang mga tail. Ang mga buong lalaking pusa ang nagpapalabas ng pinakamalaking scent. Kung ang sekreto mula sa mga scent gland ay ang allergen, ang mga taong allergic ay dapat na pinakamatolerable sa mga spayed na babaeng pusa.",
  "Hindi iniisip ng mga pusa na sila ay maliliit na tao. Iniisip nila na tayo ay malalaking pusa. Ito ay nakakaapekto sa kanilang gawi sa maraming paraan.",
  "Ang mga pusa ay naaapektuhan ng sakit sa ngipin at ng dental caries. Dapat ay mayroon silang paglilinis ng ngipin sa pamamagitan ng doktor o ng dentista ng pusa nang isang beses sa isang taon.",
  "Maraming tao ang natatakot na mahawa ng protozoan na sakit na Toxoplasmosis mula sa mga pusa. Ang sakit na ito ay maaaring magdulot ng sakit sa tao, ngunit mas seryoso, maaaring magdulot ng mga birth defects sa mga hindi pa ipinanganak. Ang Toxoplasmosis ay isang karaniwang sakit, minsan ay naiipon sa pamamagitan ng dumi ng mga pusa. Ito ay karaniwang dulot ng pagkain ng hilaw o rare na baka. Ang mga buntis na babae at mga taong may depressed na immune system ay hindi dapat hawakan ang cat litter box. Maliban sa iyon, walang dahilan para iwasan ang mga pusa.",
  "Ang ninuno ng lahat ng mga domestic na pusa ay ang African Wild Cat na nananatili pa rin hanggang ngayon.",
  "Sa sinaunang Ehipto, ang pagpatay ng isang pusa ay isang krimen na mapaparusahan ng kamatayan.",
  "Sa sinaunang Ehipto, ang mga mumo ay ginawa mula sa mga pusa, at ang mga namamatay na daga ay inilagay sa kanilang mga libingan. Sa isang sinaunang lungsod, mahigit sa 300,000 na mumo ng pusa ang natagpuan.",
  "Sa Gitnang Panahon, sa Festival ng Santo Juan, ang mga pusa ay sinusunog buhay sa mga plaza ng bayan.",
  "Ang unang palabas ng pusa ay noong 1871 sa Crystal Palace sa London.",
  "Ngayon ay mayroong halos 100 iba't ibang uri ng domestic na pusa.",
  "Tulad ng mga ibon, may kakayahang pagbabalik ng mga pusa na gumagamit ng kanilang biyolohikal na orasan, ang anggulo ng araw, at ang magnetikong kampo ng Daigdig. Ang isang pusa na inilipat malayo mula sa kanyang tahanan ay maaaring bumalik dito. Ngunit kung ang may-ari ng isang pusa ay lumipat malayo mula sa kanyang tahanan, hindi makakahanap ng mga ito ang pusa.",
  "Inililigpit ng mga pusa ang kanilang dumi upang itago ang kanilang mga landas mula sa mga manananggal.",
  "Ang mga pusa ay nagtutulog ng 16 hanggang 18 na oras kada araw. Kapag natutulog ang mga pusa, patuloy pa rin silang alerto sa mga paparating na stimuli. Kung sasapakin mo ang pwet ng natutulog na pusa, tatanggapin nito ito nang tama.",
  "Maliban sa pag-amoy sa pamamagitan ng kanilang ilong, maaaring amuyin ng mga pusa ang mga bagay sa pamamagitan ng isang karagdagang organ na tinatawag na Jacobson's organ, na matatagpuan sa itaas na bahagi ng bibig.",
  "Ang chlorine sa sariwang tubig ay nagpapalala sa mga sensitibong bahagi ng ilong ng pusa. Pabayaan ang tubig na tapos na magpahinga ng 24 oras bago ibigay sa isang pusa.",
  "Si Abraham Lincoln mahilig sa mga pusa. May apat siyang mga pusa habang siya ay nakatira sa White House.",
  "Takot si Julius Ceasar, Henri II, Charles XI, at Napoleon sa mga pusa.",
  "Ang mga pusa ay may karaniwang 24 na balbas pisngi, na nakalatag sa apat na pahalang na hanay sa bawat panig.",
  "Ang salitang 'cat' sa iba't ibang wika: French: chat; German: katze; Italian: gatto; Spanish/Portugese: gato; Yiddish: kats; Maltese: qattus; Swedish/Norwegian: katt; Dutch: kat; Icelandic: kottur; Greek: catta; Hindu: katas; Japanese:neko; Polish: kot; Ukranian: kotuk; Hawiian: popoki; Russian: koshka; Latin: cattus; Egyptian: mau; Turkish: kedi; Armenian: Gatz; Chinese: mao; Arabic: biss; Indonesian: qitta; Bulgarian: kotka; Malay: kucing; Thai/Vietnamese: meo; Romanian: pisica; Lithuanian: katinas; Czech: kocka; Slovak: macka; Armenian: gatz; Basque: catua; Estonian: kass; Finnish: kissa; Swahili: paka.",
  "Ipinapakita ng mga estadistika na ang mga mahilig sa hayop sa nakaraang mga taon ay nagpakita ng pabor sa mga pusa kaysa sa mga aso!",
  "Maaaring matutunan ng mga pusa na lumakad na may suot na leash, ngunit kailangan ng maraming oras at pasensya upang matutunan nila ito. Mas madali para sa kanila na matutunan ito kung mas bata pa sila.",
  "Hindi palaging nangangahulugan ng kaligayahan ang pag-uugoy. Maaaring ibig sabihin ng pag-uugoy ng pusa na nasa kalunus-lunos na kalagayan siya tulad ng panahon ng pagpapanganak. Ang mga alagang pusa ay uugoy sa kanilang ina upang ipaalam sa kanya na sapat ang gatas nila habang nagpapasuso. Ang pag-uugoy ay isang proseso ng paghinga at pag-ihi, kadalasan ginagawa habang nakasara ang bibig.",
  "Ang halamang catnip ay naglalaman ng isang langis na tinatawag na hepetalactone na ginagawa para sa mga pusa ang kung ano ang marijuana sa ilang tao. Hindi lahat ng pusa ay nagre-react dito; ang mga nagre-react ay parang nasa trance-like state. Ang positibong reaksyon ay nagpapakita sa pamamagitan ng pag-sniff ng catnip, pag-dila, pag-kagat, pag-chew, pag-rub at pag-gulong nito nang paulit-ulit, pag-purr, pag-meow at kahit pag-talon sa hangin.",
  "Sa lahat ng mga uri ng mga pusa, ang domestic na pusa ang tanging uri na makapag-tatag ng kaniyang pakpak habang naglalakad. Lahat ng mga uri ng mga wild na pusa ay nagtatag ng kanilang pakpak nang pahalang o nakatago sa pagitan ng kanilang mga binti habang naglalakad.",
  "Ang masayang pusa ay nag-aangat ng kanyang buntot nang mataas at matatag",
  "Halos 10% ng mga buto ng isang pusa ay nasa kanyang buntot, at ang buntot ay ginagamit upang mapanatili ang balanse.",
  "Ang mga pamilya ng pusa ay karaniwang naglalaro ng pinakamahusay sa pantay na bilang. Ang mga pusa at bata ng pusa ay dapat na ma-acquire sa pares kung maaari.",
  "Ang tsokolate na pangluto ay ang pinakamaligalig na tsokolate para sa iyong pusa.",
  "Bantayan mo ang pulse ng iyong pusa sa loob ng likod ng hita, kung saan nag-uugnay ang binti sa katawan. Normal para sa mga pusa: 110-170 na pulso bawat minuto.",
  "Ang mga Jaguar ang tanging malalaking pusa na hindi nag-uugoy.",
  "Ang field of vision ng isang pusa ay tungkol sa 185 degrees.",
  "Ang mga pusa ay may indibidwal na mga paborito para sa pag-gagatas ng mga ibabaw at mga anggulo. Ang ilan ay mga pahalang na gagatas habang ang iba ay nagpapatupad ng kanilang mga kuko nang patayo.",
  "Ang Maine Coone ang tanging lokal na Amerikanong may mahabang buhok na uri.",
  "Ang Maine Coon ay 4 hanggang 5 beses na mas malaki kaysa sa Singapura, ang pinakamaliit na uri ng pusa.",
  "Inaakala na ang pangalan ng Tabby cats ay mula sa Attab, isang distrito sa Baghdad, ngayon ay ang kabisera ng Iraq.",
  "Ang mga nababawing kuko ay isang pisikal na penomena na nag-iiba sa mga pusa sa iba pang rehiyon ng hayop. Sa pamilya ng pusa, tanging ang mga cheetah lamang ang hindi nakakabawi ng kanilang mga kuko.",
  "Hindi lahat ng pusa ay nakakakuha ng 'high' mula sa catnip. Kung ang isang pusa ay sumasagot dito ay nakasalalay sa recessive gene: walang gene, walang saya.",
  "Ang pusa ay maaaring tumakbo sa halos tatlumpung isang milya kada oras.",
  "Sa sinaunang Ehipto, kapag namatay ang isang pamilyang pusa, lahat ng miyembro ng pamilya ay magpapakulay ng kanilang mga kilay bilang isang tanda ng pagluluksa.",
  "Ang mga pusa ay naging domestikado nang kalahati ng panahon kumpara sa mga aso.",
  "Isang paniniwala ay ang mga balahibo sa pisngi ng pusa ay isang uri ng radar na tumutulong sa pusa na sukatin ang espasyo na pupuntahan nito.",
  "Ang isang pusa ay maaaring mag-gastos ng limang oras o higit pa sa isang araw para sa pag-aalaga sa sarili nito.",
  "Lahat ng mga pusa ay may tatlong set ng mahabang buhok na sensitibo sa presyon - whiskers, mga kilay, at ang mga buhok sa pagitan ng kanilang paw pads.",
  "Parehong tao at pusa ay may magkatulad na mga rehiyon sa utak na responsable para sa emosyon.",
  "Ang utak ng isang pusa ay mas katulad sa utak ng isang tao kaysa sa utak ng isang aso.",
  "Ang isang pusa ay mayroong higit na mga buto kaysa sa isang tao; ang mga tao ay may 206, at ang pusa - 230.",
  "Ang mga pusa ay mayroong 30 vertebrae--5 na higit pa kaysa sa mga tao.",
  "Ang mga pusa ang pinakapopular na alagang hayop sa Estados Unidos: Mayroong 88 milyong alagang pusa at 74 milyong aso.",
  "Ang mga pusa ay mayroong mahigit sa 20 kalamnan na nagkokontrol sa kanilang mga tenga.",
  "Isang grupo ng mga pusa ay tinatawag na clowder.",
  "May mga pusa na nakaligtas sa pagbagsak mula sa mahigit sa 32 palapag (320 metro) papunta sa kongkreto.",
  "Ang mga pusa ay nagtutulog ng 70% ng kanilang buhay.",
  "Isang pusa ang naging mayor ng Talkeetna, Alaska, sa loob ng 15 taon. Ang pangalan niya ay Stubbs.",
  "Isang pusa ang nagkandidato bilang alkalde ng Mexico City noong 2013.",
  "Sa mga tigre at tabby, ang gitna ng dila ay nakatakip sa mga spines na nakaharap sa likuran, ginagamit para sa pag-break off at pagkakapit ng karne.",
  "Kapag ang mga pusa ay nag-grimace, kadalasan ay 'taste-scenting' sila. Mayroon silang ekstra organ na, sa pamamagitan ng ilang kontrol sa paghinga, na nagpapahintulot sa mga pusa na taste-sense ang hangin.",
  "Hindi nakakatikim ang mga pusa ng matamis.",
  "Ang pag-aari ng isang pusa ay maaaring mabawasan ang panganib ng stroke at atake sa puso ng hanggang sa isang ikatlong bahagi.",
  "Mayroon tala sa Wikipedia ng pag-iyak ng isang pusa dahil, bakit hindi?",
  "Ang pinakamalaking pusa sa mundo ay may haba na 48.5 pulgada. https://www.youtube.com/watch?v=gc5M0aGc_EI",
  "Ang mga ebidensya ay nagpapahiwatig na ang mga alagang pusa ay nasa paligid mula pa noong 3600 B.C., 2,000 taon bago ang mga Faraon ng Egypto.",
  "Ang pag-ungol ng isang pusa ay maaaring maging isang uri ng pagpapagaling sa sarili, dahil maaari itong maging isang tanda ng kaba pati na rin ng kasiyahan.",
  "Gayundin, ang dalas ng pag-purr ng isang domestic cats ay pareho sa dalas kung saan ang mga kalamnan at buto ay nagre-repair sa sarili nila.",
  "Ang mga matatandang pusa ay nag-ngingiyaw lamang upang makipag-ugnayan sa mga tao.",
  "Ang pinakamayamang pusa sa mundo ay nagkakahalaga ng $13 milyon matapos na mamatay ang kanyang tao at mag-iwan ng kanyang kayamanan sa kanya.",
  "Ang iyong pusa ay nakikilala sa iyong boses ngunit masyadong astig para magpakita ng pag-aalala (malamang dahil astig sila).",
  "Ang mga pusa ay madalas na hindi tolerante sa lakto, kaya huwag na huwag silang bigyan ng gatas!",
  "Maaari ang mga pusa na lumukso ng hanggang sa anim na beses ang haba nila.",
  "Nag-ambag ang mga pusa sa pagkawala ng 33 iba't ibang uri ng species.",
  "Maaaring uminom ng tubig-dagat ang mga pusa upang mabuhay.",
];

const langName = "tagalog",
  langISO = "tl",
  langLocale = "fil",
  langLocaleName = "Filipino";

module.exports = {
  langName,
  langISO,
  langLocale,
  langLocaleName,
  code: `${langISO}-${langLocale}`,
  codeName: `${langName} (${langLocaleName})`,
  facts: facts,
};
