const facts = [
    "Árið 1987 tóku kettir fram úr hundum sem helsta gæludýr Ameríku.",
    "Kettir sem lifa saman nudda stundum hausunum sínum saman til að sýna að þeir hafi enga ætlun að slást. Ungir kettir gera þetta oftar, sérstaklega þegar þeir eru spenntir.",
    "Kattamæður kenna kettlingum sínum að nota kattasandkassa.",
    "Hvernig þú kemur fram við kettlinga snemma á ævileiðinni hefur áhrif á persónuleikann þeirra seinna í lífinu.",
    "Þvert á almenna trú þá er kötturinn félagsdýr. Kettir sem eru gæludýr bregðast við orðum og virðast njóta samveru manneskja.",
    "Kettir geta lifað í 20 eða fleiri ár í réttu yfirlæti, en meðal líftimi húskattar er 14 ár.",
    "Gelding katta bætir 2 eða 3 árum við líftíma þeirra.",
    "Kettir, sérstaklega eldri kettir, geta fengið krabbamein. Oft er hægt að meðhöndla sjúkdóminn með góðum árangri.",
    "Kettir geta ekki bragðað sætindi.",
    "Kettir verða að hafa fitu í fæðunni sinni þar sem þeir geta ekki framleitt hana sjálfir.",
    "Algengar húsplöntur sem eru eitraðar köttum eru meðal annars: Bergflétta, íris, mistilteinn og ýviður.",
    "Tylenol og súkkulaði eru bæði eitruð köttum.",
    "Margir kettir geta ekki melt kúamjólk almennilega. Mjólk og mjólkurvörur gefa þeim niðurgang.",
    "Meðal máltíð kattar jafnast á við um 5 mýs",
    "Kettir geta fengið bandorma frá því að borða flær. Ormarnir lifa ævilangt í kettinum, eða þangað til þeir eru fjarlægðir með lyfjum. Þeir fjölga sér með því að varpa hlekk af löngum líkama sínum. Þessi hlekkur skríður út um rassgat kattarins og varpar hundruðum eggja. Þessi egg eru borðuð af flóalirfum og hringrásin heldur áfram. Mannverur geta fengið þessa bandorma líka, en bara ef þeir innbyrða flærnar. Kettir með bandorma ættu að vera ormahreinsaðir af dýralækni.",
    "Kettir geta fengið bandorma frá því að borða mýs. Ef að kötturinn þinn nær mús er best að taka fenginn af honum.",
    "Tegund af AIDS er til í köttum.",
    "Litur endanna á Síamsköttum er hitatengdur. Köld svæði eru dekkri.",
    "Síamskettir fæðast hvítir vegna hitans í legi móður þeirra fyrir fæðingu. Hitinn kemur í veg fyrir að endar kattanna dekkist",
    "Fólk sem er með ofnæmi fyrir köttum er í rauninni með ofnæmi fyrir munnvatni eða flösu kattanna. Ef að kettir eru þvegnir reglulega höndlar fólk með ofnæmi þá mun betur.",
    "Rannsóknir sýna að ofnæmisvaki katta er tengdur lyktarkirtlum þeirra. Kettir eru með lyktarkirtla á andlitinu sínu og á endanum á skottinu sínu. Karlkyns kettir gefa frá sér mesta lykt. Ef að seytingin frá lyktarkirtlunum er ofnæmisvaki, þá ætti fólk með ofnæmi að þola kvenkyns ketti best.",
    "Kettir halda ekki að þeir séu lítið fólk. Þeir halda að við séum stórir kettir. Þetta hefur áhrif á hegðun þeirra á marga vegu.",
    "Kettir geta fengið tannholdssjúkdóma eða tannskemmdir. Þeir ættu að fá tannhreinsun frá dýralækni eða kattatannlækni árlega.",
    "Margir óttast að smitast af Bogfrymlasótt frá köttum. Þessi sjúkdómur getur ollið veikindum í mannfólki, en öllu alvarlegra getur hann valdið fæðingargöllum í ófæddum börnum. Bogfrymlasótt er algengur sjúkdómur, stundum dreift í gegnum kattaskít. Oftar er það hinsvegar fengið frá því að borða hrátt eða lítið eldað nautakjöt. Óléttar konur bælt ónæmiskerfi ættu ekki að snerta kattasandkassa. Þess utan er engin ástæða fyrir því að fólk í þeirri stöðu ætti að forðast ketti.",
    "Forfeður allra katta eru Afrískir Villikettir, sem að eru enn til í dag.",
    "Í Egyptalandi til forna lá dauðadómur við því að drepa kött.",
    "Í Egyptalandi til forna voru gerðar múmíur af köttum og smurðar mýs lagðar með þeim í grafhýsin þeirra. Í einni fornri borg fundust yfir 300.000 kattarmúmíur.",
    "Á miðöldum, meðan Jónsmessunótt stóð yfir, voru kettir brenndir lifandi á bæjartorgum.",
    "Fyrsta kattarsýningin var haldin 1871 í Crystal Palace í Lundúnum.",
    "Í dag eru um 100 ólíkar tegundir heimiliskatta.",
    "Líkt og fuglar eru kettir með innbyggðan leiðarvísi sem að miðar sig við líffræðilega klukku þeirra, stöðu sólar og segulsvið jarðar. Köttur tekinn langt að heiman getur því ratað heim. En ef að kattareigandi flytur langt frá heimili sínu getur kötturinn ekki fundið hann.",
    "Kettir grafa úrganginn sinn til að fela slóð sína frá rándýrum.",
    "Kettir sofa 16 til 18 tíma á dag. Þegar kettir eru sofandi eru þeir enn vakandi fyrir komandi áreiti. Ef þú potar í skott mun hann svara í samræmi við það.",
    "Ásamt því að geta þefað með nefinu geta kettir fundið lykt með auka líffæri sem kallast Jacobson-líffærið sem er staðsett á efri fleti munns þeirra.",
    "Klór í kranavatni ertir viðkvæma hluta af nefi katta. Leyfðu kranavatni að sitja í 24 tíma áður en þú gefur kettinum það.",
    "Abraham Lincoln elskaði ketti. Hann átti 4 af þeim meðan hann bjó í Hvíta húsinu.",
    "Júlíus Sesar, Henry II, Charles XI og Napóleon voru allir hræddir við ketti.",
    "Kettir hafa að meðaltali 24 veiðihár, raðað í 4 láréttar raðir á hvorri hlið.",
    "Orðið 'köttur' í mismunandi tungumálum: Franska: chat; Þýska: katze; Ítalska: gatto; Spænska/Portúgalska: gato; Jiddíska: kats; Maltneska: qattus; Sænska/Norska: katt; Hollenska: kat; Grískur: catta; Hindí: katas; Japanese:neko; Pólska: kot; Úkraínska: kotuk; Hawaiíska: popoki; Rússneska: koshka; Latína: cattus; Egypska: mau; Tyrkneska: kedi; Armenska: Gatz; Kínverska: mao; Arabíska: biss; Indonesíska: kucing; Búlgarska: kotka; Malaí: kucing; Tælenska/Víetnamska: meo; Rúmenska: pisica; Litáíska: katinas; Tékkneska: kocka; Slóvakíska: macka; Baskneska: catua; Eistneska: kass; Finnska: kissa; Svahíli: paka.",
    "Tölfræði gefur til kynna að dýraelskendur taki ketti fram yfir hunda á síðustu árum!",
    "Hægt er að kenna köttum að ganga í taum, en oft á tíðum þarf mikla þolinmæði til að kenna þeim það. Því yngri sem kötturinn er því auðveldara er fyrir þá að læra það.",
    "Það að mala þýðir ekki alltaf hamingja. Mölun hjá ketti gæti þýtt að hann sé í miklum sársauka eins og við fæðingu. Kettlingar mala til að láta móður sína vita að þeir séu ekki að fá næga mjólk á spena. Það að mala er ferli af því að anda inn og út, vanalega með lokaðan munn. En ekki örvænta, ef að kötturinn þinn er að mala meðan þú ert að klappa honum og halda honum nálægt þér - þá er þetta hamingjusamur köttur!",
    "Kattarmintuplantan inniheldur olíu sem kallast nepetalactones sem gerir það sama fyrir ketti og maríjúana gerir fyrir sumt fólk. Ekki allir bregðast eins við en þeir sem gera það virðast fara í trans. Jákvæð viðbrögð frá ketti við kattarmintu getur verið að þefa, sleikja, bíta, naga, nudda og rúlla sér upp úr kattarmintunni, mala, mjálma og jafnvel stökkva upp í loft.",
    "Af öllum kattartegundum er heimiliskötturinn sá eini sem getur haldið skottinu sínu lárétt meðan hann labbar. Allar villtar kattategundir halda skottinu sínu lárétt eða á milli lappanna sinna meðan þeir labba.",
    "Hamingjusamur köttur heldur skotti sínu hátt og stöðuglega.",
    "Nánast 10% beina kattar eru í skotti hans og er skottið notað til að halda jafnvægi.",
    "Kattarfjölskyldur leika vanalega best saman í jöfnum tölum. Kettir og kettlingar ættu að vera fengnir í pörum ef möguleiki er á því.",
    "Bökunarsúkkulaði er hættulegasta súkkulaðið fyrir ketti.",
    "Þú athugar með púlsinn á kettinum þínum á innra aftara læri, þar sem löppin tengist við líkamann. Venjulegt fyrir ketti: 110-170 slög á mínútu.",
    "Jagúarar eru einu stóru kettirnir sem öskra ekki.",
    "Sjónarsvið katta er um 185 gráður.",
    "Kettir eru mismunandi með hvernig þeir klóra fleti. Sumir klóra lárétt meðan aðrir gera það lóðrétt.",
    "Maine Coon kattategundin er eina innfædda Ameríska kattategundin með langt hár.",
    "Maine Coon kattategundin er 4 til 5 sinnum stærri en Singapura tegundin sem er minnsta kattategundin.",
    "Tabby kettir eru taldir hafa fengið nafnið sitt frá Attab, hverfi í Baghdad, sem er núna höfuborgin í Írak.",
    "Inndraganlegar klær eru líkamlegt fyrirbæri sem að skilja ketti frá restinni af dýraríkinu. Í kattarfjölskyldunni geta einungis blettatígrar ekki dregið inn klærnar sínar.",
    "Það fara ekki allir kettir í 'vímu' af kattarmintu. Það ræðst af víkjandi geni: ekkert gen, engin gleði.",
    "Kettir geta hlaupið á upp að 50 km/h.",
    "Í Egyptalandi til forna, þegar fjölskyldukötturinn dó tóku allir fjölskyldumeðlimir sig til og rökuðu af sér augabrúnirnar til merkis um að þau væru að syrgja.",
    "Kettir hafa einungis verið tamdur um helminginn af tímanum sem hundar hafa verið það.",
    "Veiðihár katta eru talin vera einskonar ratsjá sem kettir nota til að mæla út svæðið sem þeir ætla að labba í gegnum.",
    "Kettir geta eytt 5 eða fleiri klukkustundum á dag í að snyrta sig.",
    "Allir kettir hafa 3 sett af hárum sem eru viðkvæm við snertingu - veiðihár, augnhár og hárin á milli loppupúðanna.",
    "Kettir og manneskjur hafa eins svæði í heilanum sem ber ábyrgð á tilfinningum.",
    "Heili kattar er líkari heila manneskju heldur en hunda.",
    "Kettir eru með fleiri bein en manneskjur; Manneskjur hafa 206 og kettir hafa 230.",
    "Kettir eru með 30 hryggjarliði--5 fleiri en manneskjur hafa.",
    "Kettir eru vinsælasta gæludýrið í Bandaríkjunum: Þar eru 88 milljón kettir sem gæludýr og 74 milljón hundar.",
    "Kettir eru með yfir 20 vöðva sem stjórna eyrunum þeirra.",
    "Á ensku kallast hópur katta 'clowder'.",
    "Það eru kettir sem hafa lifað af fall úr yfir 320 metra hæð á steypu.",
    "Kettir sofa 70% ævi sinnar.",
    "Köttur hefur verið bæjarstjóri Talkeetna í Alaska í 15 ár. Hann heitir Stubbs.",
    "Það var köttur sem bauð sig fram til borgarstjóra Mexíkóborgar árið 2013.",
    "Í tígrisdýrum og tabby köttum er miðjan á tungum þeirra þakin afturvísandi oddum sem eru notaðir til að slíta af og ná kjöti.",
    'Þegar kettir gretta sig eru þeir vanalega að "smakka loftið". Þeir eru með sérstakt líffæri, sem að með sérstakri öndun, leyfir kettinum að "smakka" loftið.',
    "Kettir finna ekki sætt bragð.",
    "Það að eiga kött getur minnkað líkur á flogakasti og hjartaáfalli um þriðjung.",
    "Wikipedia er með upptöku af ketti að mjálma afþví að afhverju ekki?",
    "Stærsti köttur sem hefur mælst er 1.23m (48.5 tommur) langur. https://www.youtube.com/watch?v=gc5M0aGc_EI",
    "Allt bendir til þess að tamdir kettir hafi verið til síðan 3600 f.Kr., 2000 árum fyrir faraóa Egyptalands.",
    "Urr katta getur verið form af sjálfsheilun, eins og það getur verið merki taugaveiklunar eða nægjusemi. Tíðni urrs kattar er sama og sú sem vöðvar og bein laga sig.",
    "Fullorðnir kettir mjálma einungis til að eiga samskipti við manneskjur.",
    "Ríkasti köttur í heimi er virði 13 milljón dollara eftir að eigandinn hans dó og erfði hann að öllum auðæfum sínum.",
    "Kötturinn þinn þekkir röddina þína en lætur eins og honum sé sama því hann er of nettur (líklega af því hann er það).",
    "Kettir eru oft með mjólkuróþol, þannig að hættið að gefa þeim mjólk!",
    "Kettir get hoppað upp að sexfalt lengd sína.",
    "Kettir geta drukkið sjávarvatn til að lifa af.",
    "Blettatígrar urra til að tjá sig líkt og heimiliskettir, þeir geta ekki öskrað líkt og stór kattardýr (t.d. ljón)."
]

const langName = "icelandic",
    langISO = "ice",
    langLocale = "is",
    langLocaleName = "Iceland";

module.exports = {
    langName,
    langISO,
    langLocale,
    langLocaleName,
    code: `${langISO}-${langLocale}`,
    codeName: `${langName} (${langLocaleName})`,
    facts: facts,
};