const facts = [
  "Em 1987, os gatos ultrapassaram os cachorros como o animal de estimação número um na America.",
  "Gatos que vivem juntos às vezes esfregam a cabeça um do outro para mostrar que não possuem nenhuma intenção de brigar. Gatos mais jovens fazem isso com mais frequência, especialmente quando estão animados.",
  "As mães gatas ensinam seus filhotes a usar a caixa de areia.",
  "O modo como você trata os gatinhos nos estágios iniciais de sua vida irá moldar seus traços de personalidade mais tarde na vida.",
  "Ao contrário da crença popular, o gato é um animal sociável. Ele reponderá a fala e mostrará que gosta da companhia humana.",
  "Quando é bem tratado, o gato pode viver 20 ou mais anos, porém, a média de vida de um gato doméstico é de 14 anos.",
  "Castrar um gato pode extender sua vida em dois ou três anos.",
  "Gatos, principalmente os mais velhos, podem ter câncer. Muitas vezes esta doença pode ser tratada com sucesso.",
  "Gatos não podem sentir o sabor doce.",
  "Gatos precisam ter gordura na dieta porque eles não conseguem produzir por conta própria.",
  "Algumas plantas que podem envenenar os gatos são: hera, iris, visco, filodendro e teixo.",
  "Paracetamol e chocolate são venenos para os gatos.",
  "Vários gatos não podem ingerir leite de vaca. Leite ou produtos derivados do leite causarão diarréia.",
  "A refeição média de comida de gato é equivalente a cerca de cinco ratos.",
  "Os gatos podem pegar tênias comendo pulgas. Esses vermes vivem dentro do gato para sempre, ou até serem removidos com medicamentos. Eles se reproduzem soltando um elo do final de seus longos corpos. Este elo rasteja para fora do ânus do gato e libera centenas de ovos. Esses ovos são injetados por larvas de pulgas e o ciclo continua. Os humanos também podem pegar essas tênias, mas apenas se comerem pulgas infectadas. Gatos com tênias devem ser vermifugados por um veterinário.",
  "Os gatos podem pegar tênias comendo ratos. Se o seu gato pegar um rato, é melhor tirar o prêmio dele.",
  "Existe uma forma de AIDS em gatos.",
  "A cor dos pontos em gatos siameses está relacionada ao calor. As áreas frias são mais escuras.",
  "Os gatinhos siameses nascem brancos por causa do calor dentro do útero da mãe antes do nascimento. Esse calor evita que os pelos dos gatinhos escureçam nas pontas.",
  "As pessoas que são alérgicas a gatos são, na verdade, alérgicas à saliva ou pêlo de gato. Se o gato residente toma banho regularmente, as pessoas alérgicas toleram melhor.",
  "Estudos agora mostram que o alérgeno a gatos está relacionado a suas glândulas odoríferas. Os gatos têm glândulas odoríferas em seus rostos e na base de suas caudas. Gatos machos geram mais cheiro. Se esta secreção das glândulas odoríferas for o alérgeno, as pessoas alérgicas devem tolerar melhor as gatas esterilizadas.",
  "Os gatos não pensam que são pessoas pequenas. Eles pensam que somos grandes felinos. Isso influencia seu comportamento de várias maneiras.",
  "Os gatos estão sujeitos a doenças gengivais e cáries dentárias. Eles devem ter seus dentes limpos pelo veterinário ou pelo dentista do gato uma vez por ano.",
  "Muitas pessoas temem contrair uma doença protozoária, a toxoplasmose, de gatos. Esta doença também pode afetar o ser humano, mas mais seriamente, pode causar defeitos congênitos no nascimento. A toxoplasmose é uma doença comum, às vezes transmitida pelas fezes dos gatos. É causada com mais frequência pela ingestão de carne crua ou malpassada. Mulheres grávidas e pessoas com baixo sistema imunológico não devem tocar na caixa de areia do gato. Fora isso, não há razão para que essas pessoas evitem gatos.",
  "O ancestral de todos os gatos domésticos é o gato selvagem africano, que ainda existe hoje.",
  "No antigo Egito, matar um gato era um crime punível com a morte.",
  "No antigo Egito, gatos também era mumificados, e ratos embalsamados eram colocados com eles em seus túmulos. Em uma cidade antiga, mais de 300.000 múmias de gatos foram encontradas.",
  "Na Idade Média, durante as festas de São João, os gatos eram queimados vivos nas praças das cidades.",
  "A primeira exposição de gatos foi em 1871 no Crystal Palace em Londres.",
  "Hoje existem cerca de 100 raças distintas de gato doméstico.",
  "Assim como os pássaros, os gatos têm uma habilidade de voltar a suas casas. Eles usam seu relógio biológico, o ângulo do sol e o campo magnético da Terra. Um gato levado para longe de sua casa pode voltar para ela. Mas se os donos de um gato se mudarem para longe de sua casa, o gato não conseguirá encontrá-los.",
  "Os gatos enterram suas fezes para cobrir seus rastros de predadores.",
  "Os gatos dormem de 16 a 18 horas por dia. Quando os gatos estão dormindo, eles ainda estão alertas aos estímulos recebidos. Se você cutucar o rabo de um gato adormecido, ele responderá de acordo.",
  "Além de cheirar com o nariz, os gatos podem cheirar com um órgão adicional chamado órgão de Jacobson, localizado na superfície superior da boca.",
  "O cloro na água da torneira irrita partes sensíveis do nariz do gato. Deixe a água da torneira descansar por 24 horas antes de dá-la a um gato.",
  "Abraham Lincoln amava gatos. Ele teve quatro deles enquanto morou na Casa Branca.",
  "Júlio César, Henrique II, Carlos XI e Napoleão tinham medo de gatos.",
  "Os gatos têm em média 24 bigodes, dispostos em quatro fileiras horizontais de cada lado.",
  "A palavra 'gato' em vários idiomas: Francês: chat; Alemão: katze; Italiano: gatto; Espanhol/Portugûes: gato; Judeu: kats; Maltês: qattus; Sueco/Norueguês: katt; Holandês: kat; Islandês: kottur; Grego: catta; Hindu: katas; Japonês: neko; Polonês: kot; Ucraniano: kotuk; Havaiano: popoki; Russo: koshka; Latim: cattus; Egípcia: mau; Turquês: kedi; Armênio: Gatz; Chinês: mao; Arábico: biss; Indonésia: qitta; Bulgariana: kotka; Malaia: kucing; Tailandesa/Vietnamita: meo; Romano: pisica; Lituana: katinas; Tcheca: kocka; Eslovaca: macka; Basca: catua; Estoniano: kass; Finlandês: kissa; Suaíle: paka.",
  "As estatísticas indicam que os amantes de animais nos últimos anos mostraram preferência por gatos em vez de cães!",
  "Os gatos podem ser ensinados a andar na coleira, mas é necessário muito tempo e paciência para ensiná-los. Quanto mais jovem for o gato, mais fácil será para ele aprender.",
  "Ronronar nem sempre significa felicidade. O ronronar pode significar que um gato está com dores terríveis, como durante o parto. O gatinho ronronará para a mãe para que ela saiba que está recebendo leite suficiente durante a amamentação. O ronronar é um processo de inspiração e expiração, geralmente realizado com a boca fechada. Mas não se preocupe, se o seu gato está ronronando enquanto você o acaricia gentilmente e o segura perto de você - esse é um gato feliz!",
  "A planta erva-dos-gatos contém um óleo chamado hepetalactona, que faz para os gatos o que a maconha faz para algumas pessoas. Nem todos os gatos reagem a ele, aqueles que parecem entrar em um estado de transe. Uma reação positiva assume a forma do gato ao cheirar a erva-dos-gatos, lamber, morder, mastigar, esfregar e rolar repetidamente, ronronar, miar e até mesmo pular no ar.",
  "De todas as espécies de gatos, o gato doméstico é a única espécie capaz de manter a cauda na vertical enquanto caminha. Todas as espécies de gatos selvagens mantêm a cauda na horizontal ou enfiado entre as pernas enquanto caminham.",
  "Um gato feliz mantém sua cauda alta e firme.",
  "Quase 10% dos ossos de um gato estão em sua cauda, ​​e a cauda é usada para manter o equilíbrio.",
  "Famílias de gatos geralmente são melhores em números pares. Gatos e gatinhos devem ser adquiridos em pares sempre que possível.",
  "O chocolate para cozinhar é o chocolate mais perigoso para o seu gato.",
  "Você verifica o pulso do seu gato na parte interna da coxa traseira, onde a perna se junta ao corpo. Normal para gatos: 110-170 batimentos por minuto.",
  "As onças são os únicos grandes felinos que não rugem.",
  "O campo de visão de um gato é de cerca de 185 graus.",
  "Os gatos têm preferências individuais para arranhar superfícies e ângulos. Alguns são arranhadores horizontais enquanto outros exercitam suas garras verticalmente.",
  "O Maine Coone é a única raça nativa americana de pelo comprido.",
  "O Maine Coon é 4 a 5 vezes maior que o Singapura, a menor raça de gato.",
  "Acredita-se que os gatos malhados tenham o nome de Attab, um distrito de Bagdá, agora capital do Iraque.",
  "Garras retráteis são um fenômeno físico que diferencia os gatos do resto do reino animal. Na família dos felinos, apenas as chitas não conseguem retrair as garras.",
  "Nem todo gato fica 'alto' com a erva-dos-gatos. Se um gato responde ou não a isso depende de um gene recessivo: sem gene, sem alegria.",
  "Um gato pode correr a cerca de trinta e uma milhas por hora.",
  "No antigo Egito, quando um gato da família morria, todos os membros da família raspavam as sobrancelhas em sinal de luto.",
  "Os gatos foram domesticados por metade do tempo que os cães.",
  "Acredita-se que os bigodes de um gato sejam uma espécie de radar, que ajuda o gato a avaliar o espaço que pretende percorrer.",
  "Um gato pode passar cinco ou mais horas por dia se lambendo.",
  "Todos os gatos têm três conjuntos de pelos longos que são sensíveis à pressão: bigodes, sobrancelhas e os pelos entre as almofadas das patas.",
  "Tanto os humanos quanto os gatos têm regiões idênticas no cérebro responsáveis ​​pelas emoções.",
  "O cérebro de um gato é mais parecido com o cérebro de um homem do que com o de um cachorro.",
  "Um gato tem mais ossos do que um ser humano. Os humanos têm 206 e os gatos 230.",
  "Os gatos têm 30 vértebras, 5 a mais que os humanos.",
  "Os gatos são os animais de estimação mais populares nos Estados Unidos: existem 88 milhões de gatos de estimação e 74 milhões de cães.",
  "Os gatos têm mais de 20 músculos que controlam suas orelhas.",
  "Um grupo de gatos é chamado de clowde, em inglês",
  "Existem gatos que sobreviveram a quedas de mais de 32 andares (320 metros) no concreto.",
  "Os gatos dormem cerca de 70% de suas vidas.",
  "Um gato é prefeito de Talkeetna, no Alasca, há 15 anos. O nome dele é Stubbs.",
  "Um gato concorreu à prefeitura da Cidade do México em 2013.",
  "Em tigres e tabbies, o meio da língua é coberto por espinhos voltados para trás, usados ​​para quebrar e agarrar a carne.",
  'Quando os gatos fazem caretas, eles geralmente "sentem o cheiro". Eles têm um órgão extra que, com algum controle da respiração, permite que os gatos sintam o sabor do ar.',
  "Gatos não podem sentir o sabor doce.",
  "Possuir um gato pode reduzir o risco de derrame e ataque cardíaco em um terço.",
  "A Wikipedia tem uma gravação de um gato miando, porque não?",
  "O maior gato do mundo media 48,5 polegadas de comprimento. https://www.youtube.com/watch?v=gc5M0aGc_EI",
  "Evidências sugerem que gatos domesticados existem desde 3600 a.C., 2.000 anos antes dos faraós do Egito.",
  "O ronronar de um gato pode ser uma forma de autocura, pois pode ser um sinal de nervosismo e também de contentamento.",
  "Da mesma forma, a frequência do ronronar de um gato doméstico é a mesma com que os músculos e os ossos se reparam.",
  "Os gatos adultos miam apenas para se comunicar com os humanos.",
  "O gato mais rico do mundo vale $ 13 milhões depois que sua humana faleceu e deixou sua fortuna para ele.",
  "Seu gato reconhece sua voz, mas se acham muito para se importar (provavelmente porque eles são).",
  "Os gatos costumam ser intolerantes à lactose, então pare de dar leite a eles!",
  "Os gatos podem saltar até seis vezes o seu comprimento.",
  "Os gatos contribuíram para a extinção de 33 espécies diferentes.",
  "Os gatos podem beber água do mar para sobreviver.",
];

const langName = "portuguese",
  langISO = "por",
  langLocale = "br",
  langLocaleName = "Brazil";

module.exports = {
  langName,
  langISO,
  langLocale,
  langLocaleName,
  code: `${langISO}-${langLocale}`,
  codeName: `${langName} (${langLocaleName})`,
  facts: facts,
};
